# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e1a85213f6ad7e590d9b50c816463434424de55a79d038cc1163dc19f1cbfec4ee58f484398e296b2ae8b3f0ad68c6f5c853572f42b3fdf1d4c94f1a6cec046

test:
  secret_key_base: fdecb818b4306f0c545bc485d1e8fb37851f3904ced391b192928eaaa433bc6c24b9242197bc7109937de9d0afd7bcb627b38a3af91b3ebc71fb6f3867960f6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
